### ISSUE TITLE
Requires react-virtualized css

### ISSUE THREAD

**Issue by noahmiller** [bvaughn/react-virtualized-select#1]
Thanks for creating this library!  It made speeding up a select menu with thousands of options a piece of cake.

It would be helpful to note in the README that the react-virtualized css is required as well as react-virtualized-select css.  Something as simple as this in the "Getting started" section:

```javascript
import 'react-virtualized/styles.css';
```

Without that styling, menu options don't appear correctly below the top 10% or so of the menu because the absolute positioning on `Grid__cell` is missing.

**Comment by dsifford** [comment]
For me, in order to get the styles to display properly, I had to also import the stylesheets from `react-select`. You may want to add that as well.

**Comment by leojh** [comment]
Made a PR for this issue: #8

**Comment by bvaughn** [comment]
Hey guys! I'm _extremely_ sorry for not seeing this issue earlier. Something got messed up somehow with my watch settings and I haven't been receiving any notifications for this project.

The README has been updated thanks to a PR from @leojh. Sorry for the confusion!
