### ISSUE TITLE
Search is too long [help wanted]

### ISSUE THREAD

**Issue by antoine35** [bvaughn/react-virtualized-select#105]
Hi !

I have a large list of options to display. The component works well but when i want to filter writing in search box, is too long (about 12 seconds to diplay one letter).
My list is composed by 250 000 items.
I can scroll and select item by click, it's juste the search which doesn't work.

If you have an idea ...
Thanks

**Comment by bvaughn** [comment]
Have you seen this other project of mine?
https://github.com/bvaughn/react-select-fast-filter-options

I think it's exactly what you're looking for. 😉

**Comment by antoine35** [comment]
i will look. thanks
