### ISSUE TITLE
Add docs for custom `optionRenderer`?

### ISSUE THREAD

**Issue by andrewmartin** [bvaughn/react-virtualized-select#106]
Hi there,

Thanks for putting this package together, it works great!

I was wondering what you thought about adding a little more detail to the `optionRenderer` on the README. I ended up figuring it out by digging through [this example file](https://github.com/bvaughn/react-virtualized-select/blob/master/source/VirtualizedSelect/VirtualizedSelect.example.js) (again, thanks!) but thought maybe others might get stuck too.

The main thing I noticed that was somewhat confusing is that it's pretty essential to add your `onClick` handler to the element:

```js
const Option = (props) => {
  const {
    option,
    option: {
      value,
    },
    selectValue,
  } = props;
return (
<div
    onClick={() => selectValue(option)}
> ...
);
```

...otherwise it won't select. Even just pointing to the example file might help. Happy to open a quick PR.  The only reason I suggest adding this is because other decorators I've used seem to infer and set a lot of defaults for you––so one might assume that your element by default will be bound to the `onClick`. Not a huge deal, but figured worth mentioning.

Thanks again for the rad work on this.

**Comment by bvaughn** [comment]
Good suggestion. I'd welcome a PR! 😄

**Comment by semireg** [comment]
FYI, the README shows `selectValue(value)` but @andrewmartin's example shows `selectValue(option)`. The docs still seem wrong, because I banged my head against it until I found this issue.

**Comment by bvaughn** [comment]
Gotcha. I didn't write that docs example (9fea5ea) but I believe you're right. I'll update it.
