### ISSUE TITLE
Custom Scrollbar style

### ISSUE THREAD

**Issue by PlayMa256** [bvaughn/react-virtualized-select#108]
Hello, first thanks for creating this component which saves us so much time.
I have a doubt, about changing the style of the scrollbar. When using just react-select, i was using the menuRenderer props, to render the scrollbar around the menu, i've tried the same approach but that failed.

```
const menuRenderer = (params) => {
	const menu = Select.defaultProps.menuRenderer(params);
	return (
		<Scrollbars>	
			{menu}
		</Scrollbars>
	);
};
```

Is there a way to use custom scrollbars around the menu options?

Thanks.

**Comment by bvaughn** [comment]
Sorry for missing this.

Custom scrollbars isn't really something I care to support. (Too little time to maintain this project and too few people asking for the feature.) If you'd like to contribute a PR, I'll consider it. 😄

**Comment by PlayMa256** [comment]
No problem, i would love to contribute, just need a little bit of guidance on what to really put my hands on.
Would be in [here](https://github.com/bvaughn/react-virtualized-select/blob/master/source/VirtualizedSelect/VirtualizedSelect.js#L64) ?

**Comment by bvaughn** [comment]
Maybe. Honestly, I'm not sure. You'd probably need to figure out the right props to pass to react-virtualized to customize its scrollbar, and then expose them here somehow.

And just to be completely transparent, if it adds a lot of complexity to this library, I probably won't want to merge it. If there's a simple-ish solution though, I'm open to considering it. 😄

**Comment by PlayMa256** [comment]
Oh, sure. I will take a loot as soon as i have some time. This would help a lot of people that needs customization there. 

Thank you for your feedback!

**Comment by omarefg** [comment]
What if you add a css file and overwrite the Select-menu-outer class? So you can add the scrollbar the styles you want.
