### ISSUE TITLE
How to provide bootstrap validation messages 

### ISSUE THREAD

**Issue by abelkbil** [bvaughn/react-virtualized-select#111]
```

<div className="form-group">
            <label>Data source type</label>
            <VirtualizedSelect
                name="dataSourceType"
                value={values.dataSourceType}
                options={dataSourceType}
                onChange={_handleSelect}
                required={true}
            />
            {
                    errors.dataSourceType && touched.dataSourceType &&
                    <FormFeedback invalid="true">{errors.dataSourceType}</FormFeedback>
            }
        </div>
```

How can i give bootstrap validation messages to  `VirtualizedSelect`
Thank you for consideration.

**Comment by bvaughn** [comment]
I don't know anything about bootstrap validation messages, but this seems more like a question for react-select. react-virtualized-select [passes most props through to the underlying select component](https://github.com/bvaughn/react-virtualized-select/blob/b561e53623ba8478cada39760ce43aeba05b3696/source/VirtualizedSelect/VirtualizedSelect.js#L55).

**Comment by abelkbil** [comment]
@bvaughn Thank you for support. I will keep you posted.
