### ISSUE TITLE
Fiddle

### ISSUE THREAD

**Issue by ekoeryanto** [bvaughn/react-virtualized-select#113]
Hello, any working jsFiddle or JsBin out there ?

**Comment by bvaughn** [comment]
Right on the main README is a link to a Code Sandbox demo.

**Comment by ekoeryanto** [comment]
@bvaughn I read the readme, but codesandbox not using umd build, I tried jsbin
following the readme, but doesn't work

here is http://jsbin.com/vojuwok/edit?html,js,console,output
