### ISSUE TITLE
handleScrollEvent not a function error

### ISSUE THREAD

**Issue by anandrikka** [bvaughn/react-virtualized-select#115]
Suddenly getting the below error

React-Virtualized-Select: 3.0.1
react-virtualized: 9.12.0
```
VirtualizedSelect.js:79 Uncaught TypeError: grid.handleScrollEvent is not a function
    at VirtualizedSelect._this.handleScroll (VirtualizedSelect.js:79)
    at Scrollbars.handleScroll (index.js:353)
```

```
<Select
        tabIndex={tabIndex}
        key={col.dataKey}
        labelKey="label"
        valueKey="id"
        style={fieldStyle}
        className={className}
        value={value}
        onChange={e => this.onChange(e)}
        autoFocus={autoFocus} // eslint-disable-line
        options={accounts}
        maxHeight={400}
      />
```

**Comment by bvaughn** [comment]
react-virtualized@9.12.0 was released 6 months ago and react-virtualized-select@3.01 was released over a year ago. It seems unlikely that these two suddenly broke without an external change of some sort. I'll need you to provide a repro (e.g. CodeSandbox) before I'll take a look. 😄

**Comment by anandrikka** [comment]
@bvaughn my package.json shows `"react-virtualized": "^8.11.4" but I installed much higher without updating package.json. Looks like I'm the culprit :smile:

**Comment by anandrikka** [comment]
@bvaughn It is version mismatch. Thank  you.

**Comment by bvaughn** [comment]
Cool. Thanks for the update!
