### ISSUE TITLE
Elements in the list are messed up when searching

### ISSUE THREAD

**Issue by SelaO** [bvaughn/react-virtualized-select#116]
I have 33300 elements that I want to place in a select (it's 3.5MB). but when scrolling through them it rolls back up after a second, and if I search for an element, they become messed up:

![2018-04-22_16-56-49](https://user-images.githubusercontent.com/21977571/39095771-a522e3e4-464e-11e8-99cd-b77ebece09ac.png)

Can this library support such scale? 
And how can I add this library to jsfiddle so I could provide a minimal reproducible example?

**Comment by bvaughn** [comment]
Looks to me at a glance like the text is wrapping and overlapping the line below.

> Can this library support such scale?

Should be fine, yes.

> And how can I add this library to jsfiddle so I could provide a minimal reproducible example?

Just fork one of the Code Sandbox examples the README links to, like this one:
https://codesandbox.io/s/91p80x10zp

**Comment by SelaO** [comment]
Look at this:

![2018-04-23_09-55-35](https://user-images.githubusercontent.com/21977571/39111139-a9dff1fe-46dc-11e8-916b-dcf227638a36.png)

This is the options I used: https://drive.google.com/file/d/1-371Xss5CYPzGe7_0YY0qWx1i2YgELp0/view?usp=sharing

It's too big to save on the site but it works if you paste it. 

It also scrolls back up after a few mouse wheel scrolls (I'm on chrome on win 10). It's also pretty slow when searching.

**Comment by SelaO** [comment]
How can I run the demo locally? 

After I create a new app with `npx create-react-app my-app`, what then?

**Comment by bvaughn** [comment]
Sorry, but I don't have a lot of time to help with creating the repro. Hopefully you can create it by forking the Code Sandbox I listed and using way less than 3.5MB of options you are using in your production app.

> It's also pretty slow when searching.

Right, because it's using a naive search function on many thousands of items. You might want to check out this project for a faster searching solution:
https://github.com/bvaughn/react-select-fast-filter-options

**Comment by SelaO** [comment]
There's also this problem where it jumps to the middle after I drag the scroll bar.

![2018-04-26_10-28-41](https://user-images.githubusercontent.com/21977571/39291755-b535dcb4-493c-11e8-9ceb-24c0b88b54dc.gif)

**Comment by kro12** [comment]
Hey, not sure if this is related but seeing issues when using custom _optionRenderer_ with virtualized select. I created a Code Sandbox example fork as suggested, please let me know if you would prefer me to open this as a separate issue.

[Forked example](https://codesandbox.io/s/1zw9jojn43)
[Youtube video of the behaviour](https://youtu.be/Egvm70XIj2M)

**Comment by bvaughn** [comment]
@kro12 The sandbox you linked to is not using the `style` param. Here's a fix: https://codesandbox.io/s/y2799p92l9

I'm closing the original issue since OP never provided a repro case.

**Comment by bvaughn** [comment]
Happy to hear it 😊 thanks for the repro. Saves a lot of time

**Comment by kro12** [comment]
Yeh, I can appreciate that 👍  **_CodeSandbox_** is so useful
