### ISSUE TITLE
Scroll bar not draggable in IE

### ISSUE THREAD

**Issue by jefvel** [bvaughn/react-virtualized-select#12]
The scrollbar is not draggable in IE browsers, I've tested it on both Edge and IE 11.
To replicate:
Visit the demo site in IE and try interacting with the scrollbar.
http://bvaughn.github.io/react-virtualized-select/

**Comment by bvaughn** [comment]
I'm very sorry for ignoring this issue for so long. My Github "watch" setting was somehow deactivated without my realizing it and I didn't receive notifications for this project.

Unfortunately I'm a bit behind because of this- but I'll try to take a look at this issue by the weekend.

**Comment by bvaughn** [comment]
This actually appears to be a shortcoming of [react-select](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L361):

```js
	handleInputBlur (event) {
		if (this.refs.menu && document.activeElement === this.refs.menu) {
```

In this case, IE11 is reporting `document.activeElement` as a _child_ of `refs.menu` but react-select expects them to be equal.

**Comment by bvaughn** [comment]
Going to close the issue _here_ and file a PR against react-select.
