### ISSUE TITLE
Optional suggestions with this component

### ISSUE THREAD

**Issue by Moejoe90** [bvaughn/react-virtualized-select#121]
Hey, very nice component. 

I want to ask if there is an option of making this select optional instead of forcing a value 
I tried looking into documentation but its not very clear

Best reagards

**Comment by bvaughn** [comment]
I believe you'll want to take a look at the [react-select](https://github.com/JedWatson/react-select) documentation. This component just renders the options it's passed. (Specifically, I believe you're looking for the `clearable` option.)
