### ISSUE TITLE
Lazy options

### ISSUE THREAD

**Issue by rivertam** [bvaughn/react-virtualized-select#125]
So I see that there's an `async` feature, but this seems to be more for searching and that kind of thing. What if I just want to only load options when the dropdown is selected? I have a UI component that is set to a sane default we know ahead of time, but I want the ability to load the other options when requested. You can kind of think of it like how Google has their account selector at the top right of their apps where it will show you the other account options you have. However, as this UI component is common within my app, I don't want it to fetch options every time it's rendered, especially because people are unlikely to change it very often.

Is such a feature available?

**Comment by bvaughn** [comment]
This seems like more of a question for react-select. This library just displays a list of options efficiently. It doesn't actually load or filter anything.

**Comment by rivertam** [comment]
@bvaughn Thanks for the quick response. I thought that was something react-virtualized-select offered specifically as it's specifically documented here, but I see now that react-select also offers it.

**Comment by bvaughn** [comment]
No problem 👍
