### ISSUE TITLE
Is there a way to get a ref to the React-Select?

### ISSUE THREAD

**Issue by Tamakimouto** [bvaughn/react-virtualized-select#126]
I'm trying to get to the menu/menuContainer from this component, is there a way to do so that I'm not seeing?

**Comment by bvaughn** [comment]
No. There is no way, currently, to get a ref to the inner select component. Sorry! 😄

If you'd like to submit a PR, I'll consider it.

**Comment by Tamakimouto** [comment]
Right as I wrote that, I found a sketchy way to get to it. 
I haven't tested enough to see if there are any consequences of accessing it like this, but so far it seems to work.

`ref={el => this.select = el._selectRef.select}`

**Comment by bvaughn** [comment]
Right. That will get it, but it might break in a future release if we ever changed that attribute (unlikely to happen though 😄)
