### ISSUE TITLE
React Select CSS Missing

### ISSUE THREAD

**Issue by JValens** [bvaughn/react-virtualized-select#127]
I have installed library as given in npm demo installation. I have also installed react-select library but when I tried to find out CSS inside 
import 'react-select/dist/react-select.css'
from node_modules. In react-select only JS file available in this directory. No CSS file inside that directory. Should I have to find out from somewhere else?

**Comment by bvaughn** [comment]
This library is compatible with react-select version 1 only. The CSS is [in the location the docs show](https://unpkg.com/react-select@1.3.0/dist/react-select.css) for v1, but not v2.
