### ISSUE TITLE
how to set the default value from the list of available (select) options

### ISSUE THREAD

**Issue by SogoGolf** [bvaughn/react-virtualized-select#128]
hi, thanks for this component really love it.

probly a dumb question but how can I set the "default" value ? i want to be able to show a value from the list of options (loaded via options prop) as soon as the  react-virtualized-select component is rendered.

**Comment by bvaughn** [comment]
This sounds like a react-select question. I believe you should be able to just set the `value` on the select component as you normally would and this should just work.

**Comment by SogoGolf** [comment]
appreciate quick reply. i should have mentioned this in my question above, but i had wrapped VirtualizedSelect so I can use it with Formik. Since I was passing in an object to the wrapped component I just needed to grab the property i needed in onChange and all was good.

**Comment by bvaughn** [comment]
Nice! Glad you got it sorted quickly 👍
