### ISSUE TITLE
Drag and dropping elements to reorder them

### ISSUE THREAD

**Issue by victornoel** [bvaughn/react-virtualized-select#129]
When doing multi-select, it could be nice to be able to reorder elements in the list.

One way to do so would be via drag-and-drop to move them.

WDYT?

**Comment by bvaughn** [comment]
Initial reaction is that it doesn't sound like too common a UX need to be able to reorder items in a select, but I'm sure there are cases when it could make sense. 😄 I don't have any time to add new features to this library though.

**Comment by victornoel** [comment]
Hehe, yes, I was actually wondering if this use case could be covered by something else but I don't think so... 

The use case is that the order of the selected elements is important in the application where the component is used, so it can be quite bothersome to add one in the middle of others.

Furthermore, adding an element to the selector is actually a long process: you choose an item in the dropdown list, then you click on it to edit and modify some metadata about it, etc, so it is not doable to just remove and re-add item in the desired order.

Do you think this would be hard to add this feature? I have not much experience with draggable elements but I could try to tackle it if you accept PRs?

**Comment by bvaughn** [comment]
No idea. If I was going to build it, I'd look into using something like [react-dnd-hoc](https://github.com/clauderic/react-sortable-hoc) which already works well with react-virtualized.

I can't promise a timely PR review or release. I'm _really_ swamped right now. Feel free to submit a PR– but you might also end up forking if you have a time sensitive need. 😄

**Comment by bvaughn** [comment]
Closing for now since this issue seems to have stalled
