### ISSUE TITLE
Return key only

### ISSUE THREAD

**Issue by jkergosi** [bvaughn/react-virtualized-select#130]
This could be my lack of understanding, but I've gone through the documentation without luck.

<VirtualizedSelect 
           labelKey='title' 
           valueKey='id' 
           simpleValue 
           options={lists.options} 
           onChange={(optionSelected) => this.setState({optionSelected})} 
           value={optionSelected} 
           clearable={true} 
           disabled={false} 
           multi={false} 
           searchable={true} 
/>

This returns "optionSelected": {"id": "`123", "title":"ABC"}

What I'm looking for is the simple key:  "optionSelected": "123"

**Comment by kvillaniholland** [comment]
does this solve your problem?
```jsx
onChange={({id}) => this.setState({optionSelected: id})}
```

**Comment by jkergosi** [comment]
> does this solve your problem?
> 
> ```js-jsx
> onChange={({id}) => this.setState({optionSelected: id})}
> ```

Thanks kvillaniholland! That worked.
