### ISSUE TITLE
Placeholder misaligned in Chrome

### ISSUE THREAD

**Issue by mallerie** [bvaughn/react-virtualized-select#132]
Using the multi-select option, the cursor shows up after the first character of the placeholder. Has anyone else seen this? Or can try to recreate it? I am only using styles from the library.

![screen shot 2018-10-26 at 11 45 18 am](https://user-images.githubusercontent.com/16726365/47581545-ac232c80-d91f-11e8-932e-7b9df06cc0a8.png)

**Comment by mallerie** [comment]
Also, I have version 3.1.3.

**Comment by mallerie** [comment]
I will submit a PR and test for all browsers if someone can recreate this issue.

**Comment by bvaughn** [comment]
Sounds like a bug with react-select. This component doesn't render that portion of the UI 😄 

Please file against react-select: https://github.com/JedWatson/react-select

**Comment by mallerie** [comment]
Sounds good.
