### ISSUE TITLE
Different height per option

### ISSUE THREAD

**Issue by freeranger** [bvaughn/react-virtualized-select#15]
I would like to be able to set the height of the options individually.
Reason:  I want to support the concept of option groups and the group header would be a different height to the other options in the list, e.g.

![image](https://cloud.githubusercontent.com/assets/1401069/16840106/baf61efc-49ca-11e6-9f08-482889897e86.png)

I have the option group working using a custom renderer with different styles depending on whether it is a group or not, but currently the height must be specified at the <VirtualizedSelect> control level so cannot be overridden per option.

The underlying controls you use support per-row height - e.g. passing in a function to calculate the height) so it would be great if this was supported by your control too.

**Comment by bvaughn** [comment]
Hi @freeranger. Sorry for the slow response. I'm traveling in Japan this week and my schedule has been a bit disrupted.

I agree that supporting a callback function for `optionHeight` would be nice.

**Comment by bvaughn** [comment]
Just remembered why I only supported a numeric property for this. It's because filtered selects may shrink smaller than the default/max height, in which case the select menu should resize to fit its content. It's harder to calculate this if the option heights are dynamic.

**Comment by bvaughn** [comment]
Still, I think it's worth adding a tiny bit of complexity to support this use case. Give me a few minutes and I'll put up a new version. :)

**Comment by bvaughn** [comment]
Hit an unexpected snag with regard to filtering. `VirtualizedSelect` only has access to an iterable set of options but not the visible (filtered) set. So its indices don't necessarily match up to what's being rendered.

**Comment by freeranger** [comment]
Hi, if the function received the option data itself rather than the index of the option then it wouldn't matter if the indices are out because you are calculating the height based on the data rather than its position.

An alternative to supporting dynamic option heights would be to support the concept of option groups and allow the height of a group to be different to the height of actual options - thus you know in advance the height of options and of groups so the overall height is easier to calculate.

**Comment by bvaughn** [comment]
Yeah, there's a tricky case here though that's a combination of the things I mentioned above. If the list has been filtered, `VirtualizedSelect` doesn't know what the filtered options are and so it can't match an index up to an option. This means it can't determine if the select menu should be shrunk b'c the number of options are smaller/shorter than the size of the select.

**Comment by bvaughn** [comment]
D'oh. Sorry. Re-reading through `Select` code and I believe I _do_ actually have those options as a parameter to `menuRenderer`. :)

**Comment by bvaughn** [comment]
This feature is now available in version `1.1.0`. Thanks for the suggestion!

A demo can be seen [here](https://bvaughn.github.io/react-virtualized-select/) with source code [here](https://github.com/bvaughn/react-virtualized-select/blob/master/source/VirtualizedSelect/VirtualizedSelect.example.js#L129-L142).

**Comment by freeranger** [comment]
@bvaughn awesome - that is exactly the functionality we need - many thanks for implementing it!

**Comment by bvaughn** [comment]
No problem! Very happy to hear it will help you out. :)

**Comment by freeranger** [comment]
don't say that - I might be back with a load more ;^)

**Comment by bvaughn** [comment]
Haha, well contributions are also welcome ;)
