### ISSUE TITLE
Uncaught TypeError: optionHeight is not a function

### ISSUE THREAD

**Issue by trekinbami** [bvaughn/react-virtualized-select#16]
When I try to run the example, Chrome gives me the following error:

`Uncaught TypeError: optionHeight is not a function`

The example at (http://bvaughn.github.io/react-virtualized-select/) seems to have the same issue.

**Comment by trekinbami** [comment]
It appears when I don't define the optionHeight property, it breaks. It requires the property to have a function as value. When i return a integer as a value from a function, it does work:

`optionHeight={() => (35)}`

**Comment by bvaughn** [comment]
Oh boy. I'll fix it momentarily.

**Comment by bvaughn** [comment]
Fixed and released as 1.1.1. Sorry for the regression! Thanks for calling it to my attention.
