### ISSUE TITLE
feat req: checkbox for multiselect

### ISSUE THREAD

**Issue by alecperkey** [bvaughn/react-virtualized-select#17]
Has this been considered?
I believe checkboxes in the dropdown are more universally understood from a UX perspective. (at least my boss' perspective)

I suppose the easiest way to achieve this could be acheived with a ::before psuedo element on the select option rows or a css rule. 

Shall I make a PR for a boolean prop which could allow this? 

regards

**Comment by bvaughn** [comment]
Couldn't you implement this with a custom option-renderer?

I'm a bit wary to add features to the core that could be implemented in userland. :)

**Comment by alecperkey** [comment]
Yes that will work. Thank you for the suggestion!

**Comment by bvaughn** [comment]
No problem! If you write something you think would be useful for others~ and you'd be willing to share it~ let's add it to a "recipes" section or something. :)
