### ISSUE TITLE
[Likely user error] - React virtualized select not loading items beyond the first 20-30 upon scrolling.

### ISSUE THREAD

**Issue by dsifford** [bvaughn/react-virtualized-select#19]
Hi there,

Until just recently, I've been using this component without any issues whatsoever. However, it seems that as soon as I converted my codebase to mobx, I've been having a strange issue where it doesn't load beyond the first 20-30 items.

There are approximately ~1300 items that are all completely available and in the correct shape when the component mounts (no async necessary).

Here's a [screen recording](https://vid.me/kxtw) of what's happening.

Here's the repo: https://github.com/dsifford/academic-bloggers-toolkit

Here's the relevant file: https://github.com/dsifford/academic-bloggers-toolkit/blob/master/src/lib/js/reference-list/components/Menu.tsx

I initially thought it might have to do with the fact that the components higher up in the tree are using the `pureRenderMixin` (actually, the new `PureComponent` to be specific), but I toggled that on and off of those to no avail.

Any ideas? Thanks so much in advance!

**Comment by bvaughn** [comment]
Hey @dsifford,

Your recording makes me guess that you aren't requiring `react-virtualized-select/styles.css`

**Comment by bvaughn** [comment]
Quickly greping the project you linked to confirms this. :)

**Comment by dsifford** [comment]
I took all css from `react-virtualized-select/styles.css` (as well as react select) and threw it in the global application css [here](https://github.com/dsifford/academic-bloggers-toolkit/blob/master/src/lib/css/collections/react-select.styl), which is bundled [here](https://github.com/dsifford/academic-bloggers-toolkit/blob/master/src/lib/css/admin.styl) and available at runtime.

Is this a no-no? And if so (if you don't mind educating me on this), why?

Thanks for the help.

**Comment by dsifford** [comment]
The reason for my decision to do that was because that was the only css that I needed to bundle with the application, and I figured it would be overkill to install `style-loader` and `css-loader` just for that.

**Comment by dsifford** [comment]
Trying to bundle using webpack now. I'll report back with the results on that in a sec.

**Comment by dsifford** [comment]
Yep, you were right. 

That makes no sense to me. I suppose I'll just stop trying to be clever and follow instructions!

**Comment by bvaughn** [comment]
Haha, no worries. It's just a common source of problem. (I've seen at least a dozen bug reports that behave the same, and the source is always missing styles, so it's easy to diagnose.)

**Comment by Haemoglobin** [comment]
Spent a long time today figuring out why I was getting the same issue, drove me crazy until I realised I was missing the 
import 'react-virtualized/styles.css'

Note, that's different to the 'react-virtualized-select/styles.css' mentioned above! It's missing from the "getting started" section, although it's mentioned in the sample part...

**Comment by bvaughn** [comment]
Oh snap. Sorry @Haemoglobin. I've just updated the README.
