### ISSUE TITLE
Creatable Virtualized Select

### ISSUE THREAD

**Issue by michalvankodev** [bvaughn/react-virtualized-select#22]
Hello

Is there any way how to use VirtualizedSelect as a renderer for Creatable from react-select? https://github.com/JedWatson/react-select/#user-created-tags

I couldn't find any example and when I read the code it looks like those components can't be composed together.

**Comment by bvaughn** [comment]
Yup. Support for this has been added in 1.4.0.

```js
import React, { Component, PropTypes } from 'react'
import { Creatable } from 'react-select'
import VirtualizedSelect from 'react-virtualized-select'

function render (props) {
  return (
    <VirtualizedSelect
      {...props}
      selectComponent={Creatable}
    />
  )
}
```

**Comment by leojh** [comment]
In case it helps anyone, props are passed to `Creatable` by assigning them to `VirtualizedSelect`
