### ISSUE TITLE
Search is very slow

### ISSUE THREAD

**Issue by kamalpatel125** [bvaughn/react-virtualized-select#23]
Hi Brian,

First of all thanks for doing great work, really appreciate this. Actually, I am using react-virtualized-select for my project for data items > 400.  I realised that search is very slow and noticeable but after using "react-select-fast-filter-options" passing down filterOptions, search becomes really fast.  

Is it not possible to integrate "react-select-fast-filter-options" into "react-virtualized-select"? So don't need to bring two packages separately and remember to pass the filterOptions. 

Regards,

Kamal Patel.

**Comment by bvaughn** [comment]
Hi @kamalpatel125,

Thanks very much for the kind words. 😀 I'm glad to hear you're finding both projects useful!

I understand your train of thought here. If you're using _react-select-fast-filter-options_ then it seems pretty likely that you'll also want to use _react-virtualized-select_. I'm not convinced you always want to use fast-filter-options though. (I think you might just want to use _react-virtualized-select_ by itself in some use-cases.)

Either way, it's a bit easier on me to keep them separate. And I think that- even if I were to combine them- the only difference would be 1 fewer NPM dependency. (I think the Api would still be pretty much the same. I don't think I could reduce it any more from what it already is.)

So for the time being, I'd prefer to keep them modular for my own convenience. 😁 Hope you understand!

Again, thanks for the kind words and I appreciate the feedback!
