### ISSUE TITLE
es6 code inclusion issues

### ISSUE THREAD

**Issue by mbrevda** [bvaughn/react-virtualized-select#28]
Trying to include VirtualizedSelect with rollup threw issues about `_default` being undefined. Changing the `jsnext:main` path to  `dist/es/VirtualizedSelect/VirtualizedSelect.js` resolved the issues. Is there any reason to include the index.js which includes another index.js instead of just exporting VirtualizedSelect.js directly?

**Comment by bvaughn** [comment]
It's a habit held over from larger projects where there is more than one component being exported.

I'm not sure I understand why rollup would be unhappy with that. It seems like a valid import/export chain.

**Comment by mbrevda** [comment]
Weird. Due to its extreme amount of issues and weirdies, I'm giving up on rollup, so feel free to close/ignore this.

**Comment by bvaughn** [comment]
No problem. 😄 I have never used it myself so I'm afraid I can't be of much help here unfortunately.
