### ISSUE TITLE
Is it possible to reduce the size of the react-virtualized dependency?

### ISSUE THREAD

**Issue by mattgrosse** [bvaughn/react-virtualized-select#29]
In an attempt to trim down the size of my bundle, I've been switching my imports to use file paths rather than destructuring assignments. I'm using webpack 1, so I think this is the only way I can achieve "tree shaking". ([I read this article](https://lacke.mn/reduce-your-bundle-js-file-size/))

I analyzed the my bundle and see that react-virtualized is being pulled in at 227k (which I assume is the entire lib) - and was wondering if there was a way to include react-virtualized-select, while only bringing in the parts of react-virtualized that it needs?

**Comment by bvaughn** [comment]
Great suggestion, @mattgrosse.

I _believe_ it may be as simple as changing this line:
```jsx
// Before
import { AutoSizer, List } from 'react-virtualized'

// After
import AutoSizer from 'react-virtualized/dist/commonjs/AutoSizer'
import List from 'react-virtualized/dist/commonjs/List'
```

I'll take a look at it later this morning. 😄

**Comment by bvaughn** [comment]
I created a simple application using create-react-app. I installed react-virtualized-select (latest) and added it to the main `App.js` file. Then I built the app and resulting JS size is 300kb.

I did the same thing, but with a version of react-virtualized-select that uses imports like the ones I mentioned above. The resulting JS size is 245kb. So it looks like we can shave a whole 55kb off of the bundled size by doing this!

Another data point ~ the UMD file size for react-virtualized-select:
* Version [2.0.1](https://unpkg.com/react-virtualized-select@2.0.1/dist/umd/): 419.9 kB
* Version [2.0.2](https://unpkg.com/react-virtualized-select@2.0.2/dist/umd/): 266.5 kB

(Keep in mind the UMD file includes lots of white space, comments, etc.)

Anyway! Very nice. This has been released as version 2.0.2 Give it a spin and let me know what you think. 😄

**Comment by mattgrosse** [comment]
Thanks Brian, that's great. I'll give it a try soon and let you know!

**Comment by mattgrosse** [comment]
@bvaughn After updating to 2.0.2, my production bundle (using UglifyJS) was about 50k smaller as well. So that's great! Glad this worked out.

**Comment by bvaughn** [comment]
Glad to hear 😄
