### ISSUE TITLE
Exposing props for the List component

### ISSUE THREAD

**Issue by dcneiner** [bvaughn/react-virtualized-select#30]
We are trying to use this component to render a large lazily loaded list. In our use case, the list could conceivably contain 5000 items, and we are only loading the first 50. We populate the list will 5000 items, but they say "Loading…" until the ajax is returned. 

Here is the problem: We need to know what rows were just rendered so we can ensure there was content for those rows. We are using react-virtualized elsewhere, and just handle `onRowsRendered` which gives us both the `overscanStartIndex` and `overscanStopIndex`. This solution works for us, but since this component does not expose a way to add props to the list directly, we had to modify it ourselves. 

Is exposing the `onRowsRendered` or a more generic `listProps` property that could be passed onto the List component something you are interested in adding? I'm happy to add the tests and send a PR if you want this, but if not, we can just use our fork.

Thanks for creating and maintaining this component!

**Comment by bvaughn** [comment]
Hm, interesting. I believe that a `...rest` type props-pass-thru would be reasonable for any props not used by the virtualized select. That way anyone wanting to make use of any other vanilla react-virtualized functionality could.

**Comment by bvaughn** [comment]
Okay. 2.1.0 has this feature via a new `listProps` property. Good suggestion! Thanks~

**Comment by dcneiner** [comment]
@bvaughn Thank you so much! I'll pull it down and try it out!
