### ISSUE TITLE
multiselect with comma in the value

### ISSUE THREAD

**Issue by DigitalMarc** [bvaughn/react-virtualized-select#32]
Hi,
First: thanks for that great component! 
If the items in the list contains comma, the default behavior of the multi selection is not correct.

**Comment by bvaughn** [comment]
You're welcome 😄

This sounds like an issue that should be filed against react-select. This library just manages the rendering of the drop-down portion of the select for efficiency. The top, input area (and the multi-select state management) is all controlled by react-select.

I _think_ this issue should be moved to there so I'm closing it as non-actionable here. Please correct me if I've misunderstood. 😁

**Comment by DigitalMarc** [comment]
That make perfect sense!
For now I've just removed the comma from the values but I set the "simpleValue" to false as well ;)
Thanks for the quick reply!

**Comment by bvaughn** [comment]
Yup! :)
