### ISSUE TITLE
Async and Creatable Options don't work in Safari

### ISSUE THREAD

**Issue by vidaaudrey** [bvaughn/react-virtualized-select#34]
I was trying the react-virtualized-select, it has been great except that the async and creatable options somehow don't work in Safari. For async, I think it's because fetch is not supported. For Creatable options, I'm not exactly sure.  Does anyone know the how to solve the problem?

**Comment by bvaughn** [comment]
Hi @vidaaudrey,

No. I see that you're correct; the demo site doesn't work on Safari. I don't know why though. Probably don't have the time to debug it any time soon. I'd welcome PRs if you do. 😄

**Comment by bvaughn** [comment]
This has since been fixed 😄
