### ISSUE TITLE
maxHeight > 200 not working

### ISSUE THREAD

**Issue by bagl** [bvaughn/react-virtualized-select#38]
Clearly the prop is passed down, but when set above 200 the popup menu is still only 200px tall.

Maybe it's an issue of react-select, but I am not sure...

**Comment by bvaughn** [comment]
This should be filed against react-select. If react-virtualized-select is passing the prop ([which it is](https://github.com/bvaughn/react-virtualized-select/blob/3e44736be7456e154b1ae0f3285bfc250c3ba5d2/source/VirtualizedSelect/VirtualizedSelect.js#L45)) then it's out of my hands. 😄

It looks like react-select sets a [max height of 200](https://github.com/JedWatson/react-select/blob/ef3a4687bc67684809c3a2648143a1c325ee987e/scss/select.scss#L30) FWIW.

**Comment by joshbuchea** [comment]
Thanks for referencing the `max-height` value in react-select 🙏 Handy!
