### ISSUE TITLE
Failed during install

### ISSUE THREAD

**Issue by workboxsoftware** [bvaughn/react-virtualized-select#42]
Just got the following errors doing an npm install:

Bobs-mbp13:react-virtualized-select bob$ npm i
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated wrench@1.5.8: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated standard-format@1.6.10: standard-format is deprecated in favor of a built-in autofixer in 'standard'. Usage: standard --fix
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> fsevents@1.0.17 install /Users/bob/dev/play/react-virtualized-select/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/bob/dev/play/react-virtualized-select/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> execSync@1.0.2 install /Users/bob/dev/play/react-virtualized-select/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

> phantomjs@1.9.20 install /Users/bob/dev/play/react-virtualized-select/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Download already available at /var/folders/gr/2v70tn7d3y974fhfthsj3xvc0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /Users/bob/dev/play/react-virtualized-select/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/gr/2v70tn7d3y974fhfthsj3xvc0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1485695719996/phantomjs-1.9.8-macosx -> /Users/bob/dev/play/react-virtualized-select/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/bob/dev/play/react-virtualized-select/node_modules/phantomjs/lib/phantom/bin/phantomjs

> spawn-sync@1.0.15 postinstall /Users/bob/dev/play/react-virtualized-select/node_modules/spawn-sync
> node postinstall

> execSync@1.0.2 install /Users/bob/dev/play/react-virtualized-select/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

> fsevents@1.0.17 install /Users/bob/dev/play/react-virtualized-select/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/bob/dev/play/react-virtualized-select/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> spawn-sync@1.0.15 postinstall /Users/bob/dev/play/react-virtualized-select/node_modules/spawn-sync
> node postinstall

> react-virtualized-select@2.3.0 prepublish /Users/bob/dev/play/react-virtualized-select
> npm run build

> react-virtualized-select@2.3.0 prebuild /Users/bob/dev/play/react-virtualized-select
> npm run lint

> react-virtualized-select@2.3.0 lint /Users/bob/dev/play/react-virtualized-select
> standard

> react-virtualized-select@2.3.0 build /Users/bob/dev/play/react-virtualized-select
> npm run build:commonjs && npm run build:css && npm run build:es && npm run build:demo && npm run build:umd

> react-virtualized-select@2.3.0 build:commonjs /Users/bob/dev/play/react-virtualized-select
> npm run clean:commonjs && cross-env NODE_ENV=production cross-env BABEL_ENV=commonjs babel source --out-dir dist/commonjs --ignore *.example.js,*.test.js,source/demo/,source/tests.js

> react-virtualized-select@2.3.0 clean:commonjs /Users/bob/dev/play/react-virtualized-select
> rimraf dist/commonjs

source/TestUtils.js -> dist/commonjs/TestUtils.js
source/VirtualizedSelect/VirtualizedSelect.js -> dist/commonjs/VirtualizedSelect/VirtualizedSelect.js
source/VirtualizedSelect/index.js -> dist/commonjs/VirtualizedSelect/index.js
source/index.js -> dist/commonjs/index.js

> react-virtualized-select@2.3.0 build:css /Users/bob/dev/play/react-virtualized-select
> postcss --use autoprefixer source/styles.css > styles.css

> react-virtualized-select@2.3.0 build:es /Users/bob/dev/play/react-virtualized-select
> npm run clean:es && cross-env NODE_ENV=production cross-env BABEL_ENV=es babel source --out-dir dist/es --ignore *.example.js,*.test.js,source/demo/,source/tests.js

> react-virtualized-select@2.3.0 clean:es /Users/bob/dev/play/react-virtualized-select
> rimraf dist/es

resolve failed:  { [Error: Cannot find module 'q-io'] code: 'MODULE_NOT_FOUND' } q-io
node_modules/nan
resolve failed:  { [Error: Cannot find module 'collections'] code: 'MODULE_NOT_FOUND' } collections
resolve failed:  { [Error: Cannot find module 'caniuse-db'] code: 'MODULE_NOT_FOUND' } caniuse-db
resolve failed:  { [Error: Cannot find module 'babel-runtime'] code: 'MODULE_NOT_FOUND' } babel-runtime
resolve failed:  { [Error: Cannot find module 'webpack-core'] code: 'MODULE_NOT_FOUND' } webpack-core
source/TestUtils.js -> dist/es/TestUtils.js
source/VirtualizedSelect/VirtualizedSelect.js -> dist/es/VirtualizedSelect/VirtualizedSelect.js
source/VirtualizedSelect/index.js -> dist/es/VirtualizedSelect/index.js
source/index.js -> dist/es/index.js
{ [Error: EISDIR: illegal operation on a directory, read] errno: -21, code: 'EISDIR', syscall: 'read' }

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/bob/.nvm/versions/node/v5.0.0/bin/node" "/Users/bob/.nvm/versions/node/v5.0.0/bin/npm" "run" "build:es"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! react-virtualized-select@2.3.0 build:es: `npm run clean:es && cross-env NODE_ENV=production cross-env BABEL_ENV=es babel source --out-dir dist/es --ignore *.example.js,*.test.js,source/demo/,source/tests.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-virtualized-select@2.3.0 build:es script 'npm run clean:es && cross-env NODE_ENV=production cross-env BABEL_ENV=es babel source --out-dir dist/es --ignore *.example.js,*.test.js,source/demo/,source/tests.js'.
npm ERR! This is most likely a problem with the react-virtualized-select package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean:es && cross-env NODE_ENV=production cross-env BABEL_ENV=es babel source --out-dir dist/es --ignore *.example.js,*.test.js,source/demo/,source/tests.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-virtualized-select
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bob/dev/play/react-virtualized-select/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/bob/.nvm/versions/node/v5.0.0/bin/node" "/Users/bob/.nvm/versions/node/v5.0.0/bin/npm" "run" "build"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! react-virtualized-select@2.3.0 build: `npm run build:commonjs && npm run build:css && npm run build:es && npm run build:demo && npm run build:umd`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-virtualized-select@2.3.0 build script 'npm run build:commonjs && npm run build:css && npm run build:es && npm run build:demo && npm run build:umd'.
npm ERR! This is most likely a problem with the react-virtualized-select package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:commonjs && npm run build:css && npm run build:es && npm run build:demo && npm run build:umd
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-virtualized-select
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bob/dev/play/react-virtualized-select/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/bob/.nvm/versions/node/v5.0.0/bin/node" "/Users/bob/.nvm/versions/node/v5.0.0/bin/npm" "i"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! react-virtualized-select@2.3.0 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-virtualized-select@2.3.0 prepublish script 'npm run build'.
npm ERR! This is most likely a problem with the react-virtualized-select package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-virtualized-select
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bob/dev/play/react-virtualized-select/npm-debug.log

**Comment by bvaughn** [comment]
I've seen this error on another machine (and for another project):
```
{ [Error: EISDIR: illegal operation on a directory, read] errno: -21, code: 'EISDIR', syscall: 'read' }
```

Despite the npm text claiming the problem is likely with react-virtualized-select, I'm fairly confident it is actually with one of its dependencies.

**Comment by workboxsoftware** [comment]
OK - Thanks.  Your routines worked fine. The problems were in the demo - I think fetching data from github - but I'm not certain.
