### ISSUE TITLE
OptionComponent

### ISSUE THREAD

**Issue by GenoD** [bvaughn/react-virtualized-select#44]
I'm having trouble with using a custom component for rendering. Using react-select I was passing a react component to filterOptions. However, with react-virtualized-select it seems it is not being used.

My current implementation is as follows:

```
const InventoryOption = React.createClass({
  propTypes: {
  children: React.PropTypes.node,
  className: React.PropTypes.string,
  isDisabled: React.PropTypes.bool,
  isFocused: React.PropTypes.bool,
  isSelected: React.PropTypes.bool,
  onFocus: React.PropTypes.func,
  onSelect: React.PropTypes.func,
  option: React.PropTypes.object.isRequired,
  },

  handleMouseDown (event) {
    event.preventDefault();
    event.stopPropagation();
    this.props.onSelect(this.props.option, event);
  },

  handleMouseEnter (event) {
    this.props.onFocus(this.props.option, event);
  },

  handleMouseMove (event) {
    if (this.props.isFocused) return;
    this.props.onFocus(this.props.option, event);
  },

  render () {
    var selectionStyle = {
			borderRadius: 3,
			display: 'inline-block',
			marginRight: 10,
			position: 'relative',
			top: -2,
			verticalAlign: 'middle',
      whiteSpace: 'pre',
      fontFamily: 'monospace',
      fontSize: 10
		};

    return (
      <div className={this.props.className}
        onMouseDown={this.handleMouseDown}
        onMouseEnter={this.handleMouseEnter}
        onMouseMove={this.handleMouseMove}
        title={this.props.option.title}>
        <span style={selectionStyle}>{this.props.option.label}</span>
      </div>
    );
  }
});

...

const { input, options, defaultValue } = this.props;
const filterOptions = createFilterOptions({ options })


<VirtualizedSelect
                      filterOptions={filterOptions}
                      optionComponent={InventoryOption}
                      options={options}
                      {...input}
                      value={input.value.value || input.value || defaultValue.value}
                      onBlur={() => { input.onBlur(input.value) } }
                      />
```

Is this feature from the original library not supported?

**Comment by bvaughn** [comment]
Yes, this is supported. You can see an example of it [here](https://github.com/bvaughn/react-select-fast-filter-options/blob/1d0da7dc9988829fd0b738af68a51deb16ed37e1/source/demo/Application.js#L55-L60). Not sure why your example isn't working, other than perhaps the `input` object you're spreading contains a `filterOptions` that's overriding the function you're passing.

**Comment by bvaughn** [comment]
Going to close this as I'm fairly confident it isn't a react-virtualized-select issue. You may consider posting an example of your widget (using Plnkr or similar) on StackOverflow or Reddit. 😄

**Comment by GenoD** [comment]
Hi @bvaughn I apologize. I meant to say that using react-select I was passing a react component to "optionComponent" and not "filterOptions". 

Using optionComponent={InventoryOption} in react-select works fine. But replacing the tabs with VirtualizedSelect loses the customer rendering.

I have updated the question

**Comment by bvaughn** [comment]
Ah, I see.

No, `optionComponent` is not a supported option for react-virtualized-select. `optionRenderer` must be used instead. 😄

**Comment by GenoD** [comment]
@bvaughn awesome. With a little more reading and examples for reference I was able to get things up and going! Thanks for the quick replies!

**Comment by bvaughn** [comment]
No problem. I am glad to hear it.

**Comment by geirsagberg** [comment]
I ran into the same problem. Maybe you could add this limitation to the README? Currently it says:

> react-select-virtualized works just like react-select. You pass it an array of options, along with any other parameters supported by the Select component.

However, if `optionComponent` is not supported, this should be mentioned as a limitation.

**Comment by bvaughn** [comment]
I'm not really using this library myself these days, but I'm happy to accept PRs that improve the documentation. Want to submit one? 😄

**Comment by geirsagberg** [comment]
@bvaughn https://github.com/bvaughn/react-virtualized-select/pull/119 Done :)
