### ISSUE TITLE
typescript types

### ISSUE THREAD

**Issue by ehartford** [bvaughn/react-virtualized-select#45]
I tried "npm install --save-dev @types/react-virtualized-select" and there is none

**Comment by bvaughn** [comment]
None of my OSS projects use TypeScript. If you would like to see types added- feel free to submit a PR 😄 

I don't plan to personally take any action on this issue though so I'm going to close it. I'll be happy to review a PR though as long as the process of publishing and updating types is automated and hooked into the process of building and releasing this lib!

**Comment by jakeboone02** [comment]
Just wanted to note that this library does have typings now:

https://www.npmjs.com/package/@types/react-virtualized-select
