### ISSUE TITLE
Uncaught TypeError: selectValue is not a function

### ISSUE THREAD

**Issue by max-mykhailenko** [bvaughn/react-virtualized-select#47]
I have this error when try to select option in dropdown. Configuration:

```jsx
<VirtualizedSelect
  multi
  onChange={this.handleSelect}
  options={options}
  placeholder={'Выберите элементы'}
  value={this.state.addValues}
/>
```

**Comment by bvaughn** [comment]
Check out the docs: https://github.com/bvaughn/react-virtualized-select/blob/master/README.md

selectValue is a required prop.

> Callback to update the selected values; for example, you may want to call this function on click.

**Comment by max-mykhailenko** [comment]
Do you mean 
`onChange={(selectValue) => this.setState({ selectValue })}` or
`selectValue	PropTypes.func`?

**Comment by max-mykhailenko** [comment]
Because `selectValue PropTypes.func` situated in `Custom Option Renderer` which mark it as custom property.

**Comment by bvaughn** [comment]
Hey @max-mykhailenko

I apologize. I was at a conference yesterday. It was pretty distracting. I misunderstand your question and my answer was quick and sloppy.

`selectValue` is one of the named parameters passed to the react-select `renderMenu` property (see [here](https://github.com/JedWatson/react-select/#effeciently-rendering-large-lists-with-windowing)). It gets passed [from react-select](https://github.com/JedWatson/react-select/blob/2249f26fbfd37f380551aaba0026274034c9b2b7/src/Select.js#L982) to the [option renderer](https://github.com/bvaughn/react-virtualized-select/blob/1c1707a8224e6bfca3b75787d4056c271858c3e9/source/VirtualizedSelect/VirtualizedSelect.js#L153) as the way to change the selected value.

I'm actually not sure why you would get the error you're mentioning. Can you repro in a Plnkr by chance? Which versions of each library do you have installed?

**Comment by max-mykhailenko** [comment]
Updating to the latest react-select solved my problem. Thanks!
Working combination:
```json
"react-select": "1.0.0-rc.3",
"react-virtualized": "9.3.0",
"react-virtualized-select": "2.4.0",
```
