### ISSUE TITLE
IE 11 issues

### ISSUE THREAD

**Issue by mtrekker** [bvaughn/react-virtualized-select#48]
IE11 is not compatible.

Launch IE, go to http://bvaughn.github.io/react-virtualized-select

I get the following error:

Minified React error #39; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=39&args[]=%20This%20may%20be%20caused%20by%20unintentionally%20loading%20two%20independent%20copies%20of%20React. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

When I debug locally with non-minified React then I get this:

Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `Select`.

When I use "react-select" instead of "react-virtualized-select" then component is working fine.

Found similar issue reference: https://github.com/facebook/react/issues/8379

It seems to be related to babel polyfill and load order ?

**Comment by bvaughn** [comment]
Should be resolved now. Just needed to polyfill a few things (eg symbol, promise) for IE.
