### ISSUE TITLE
Getting all option values when selecting an option

### ISSUE THREAD

**Issue by AchinthaReemal** [bvaughn/react-virtualized-select#52]
Is there a way to get the object value of a selection when we provide the options in the following manner.

```
let options = [];
dataFromServer.forEach(user => {
    options.push({"label": user.firstName, "value": user.profileId, "permissions": user.permissions});
});
```

and after adding an onChange like below,

`onChange={ (selection) => { console.log('Selection:  ', selection) }`

I would only get the label value of the selection, not the entire option which was selected.

**Comment by bvaughn** [comment]
Hey @AchinthaReemal.

`VirtualizedSelect` [passes the entire option to `selectValue `](https://github.com/bvaughn/react-virtualized-select/blob/60c934dccc279db717d2df45184b0bdff4e15a20/source/VirtualizedSelect/VirtualizedSelect.js#L171) which seems to also [pass it on (in full) to the `onChange` prop](https://github.com/JedWatson/react-select/blob/881873c10fc91aea9b0982c188a12360ebdd349c/src/Select.js#L609).

If you'd like to link a Plnkr that reproduces what you're describing with expected vs actual behavior, I'll be happy to take a look.
