### ISSUE TITLE
#56 broke my app

### ISSUE THREAD

**Issue by the-spyke** [bvaughn/react-virtualized-select#57]
I've used `VirtualizedSelect` like so:

```
const VirtualizedSelect = require("react-virtualized-select").default;
```

With update to 2.4.1 my app crashes because the import returns `undefined` and I need to remove the `.default`.

**Comment by bvaughn** [comment]
Sorry. Sounds like an unintended side effect of PR #56.

**Comment by bvaughn** [comment]
FWIW I tested with the `import` syntax (as shown on the docs) and the UMD syntax. I'm sorry for not testing with `require` as you mention.

Added a backwards-compat fix as version 2.4.2

**Comment by the-spyke** [comment]
@bvaughn Thank you!

**Comment by mbrevda** [comment]
I just updated and am getting the following error: `Cannot assign to read only property 'exports' of object`

<img width="838" alt="screen shot 2017-04-27 at 5 43 56 pm" src="https://cloud.githubusercontent.com/assets/293004/25488958/1f03821c-2b71-11e7-859d-4b0b4475e9b9.png">

Any ideas?

**Comment by bvaughn** [comment]
Rats ☹️ 

Not off the top. Seems like PR #56 has caused more trouble than it solved. Maybe the best approach at this point is to revert that and try to fix the UMD bundle some other way.

Happy to accept any PRs for this if you can get to it before I find time.

**Comment by mbrevda** [comment]
Should I just revert for now?

**Comment by bvaughn** [comment]
That will "break" the UMD build. Although I guess that's better than this.

I'd prefer a _fix_ but a revert would also be ok I guess...
