### ISSUE TITLE
Using an old version of react-virtualized

### ISSUE THREAD

**Issue by bradbirnbaum** [bvaughn/react-virtualized-select#58]
Can you please upgrade to 9.x?   Being locked to 8.x is causing my project to include `react-virtualized` twice since we are using 9.7.3.

**Comment by bvaughn** [comment]
Just released v3. No changes at all except for dependencies. Enjoy.

In the future, please feel free to submit PRs for this sort of thing. I'm happy to review them.

**Comment by bradbirnbaum** [comment]
Awesome - thanks so much

**Comment by bvaughn** [comment]
No problem. Had been meaning to get around to this.
