### ISSUE TITLE
Make mention in README.md of additional required css files

### ISSUE THREAD

**Issue by leojh** [bvaughn/react-virtualized-select#6]
In addition to importing ```react-virtualized-select/styles.css``` which the documentation makes note of, ```react-virtualized/styles.css```and ```react-select/dist/react-select.css``` also seem to be required.

I can do a PR to modify readme file if my observations are consistent with the community's.

**Comment by ZhangCongjie** [comment]
+1!
`react-virtualized/styles.css` and `react-select/dist/react-select.css` also need to be required but readme file doesn't include.

**Comment by jsnmoon** [comment]
Agreed, making this more explicit on the README may ease confusion among newcomers.

**Comment by leojh** [comment]
Made a PR for this issue: #8

**Comment by bvaughn** [comment]
I'm _extremely_ sorry for not seeing this issue earlier. Somehow my GH "watch" got removed from this project and I haven't been receiving any notifications.

@leojh 's PR has been merged! README now has this listed.
