### ISSUE TITLE
Provide default option container component to consumers

### ISSUE THREAD

**Issue by seansfkelley** [bvaughn/react-virtualized-select#62]
The `optionRenderer` option is a very flexible extensibility point, but it's tedious to use if you want to do something simple like e.g. wrap the content in a `span` or just add another classname to some options: you end up having to reimplement [`_optionRenderer`](https://github.com/bvaughn/react-virtualized-select/blob/master/source/VirtualizedSelect/VirtualizedSelect.js#L154..L187) if you want to keep the default class names and mouse interactions. It'd be nice if there were some kind of `DefaultOption` component that also accepted `children` so I could do something like:

```jsx
renderOption(params) {
  return <DefaultOption {...params}><span>foo</span></DefaultOption>;
}
```

**Comment by bvaughn** [comment]
You could put a React element in `option.label`. The only thing `labelKey` is used for is to grab a child to put in the rendered option. That child is usually a string but it doesn't _have_ to be.

**Comment by seansfkelley** [comment]
Hm, interesting, didn't think of that. It works for most cases, but not if I want to (for example) add a class name to the default component.

**Comment by bvaughn** [comment]
If you'd like to create a PR that does this (in a 100% backwards compatible way) I'll be happy to review it.

**Comment by bvaughn** [comment]
Closing due to lack of interest 😄
