### ISSUE TITLE
react-virtualized-select gitter 404s / no longer active

### ISSUE THREAD

**Issue by turnerniles** [bvaughn/react-virtualized-select#65]
Hi @bvaughn, the react-virtualized-select gitter [link](https://gitter.im/bvaughn/react-virtualized-select) in the [CONTRIBUTING.md](https://github.com/bvaughn/react-virtualized-select/blob/master/CONTRIBUTING.md) 404s. Perhaps the file should point to the react-virtualized Slack channel?

**Comment by bvaughn** [comment]
This channel never had a Gitter. I probably just accidentally copied that file when setting up the repo. To be honest, I don't think this project requires a support channel. It's tiny. Questions should almost always be directed to react-select or sometimes react-virtualized. 😄 Sorry for the confusion!

**Comment by bvaughn** [comment]
Removed reference to Gitter in fbdb83f

**Comment by turnerniles** [comment]
Ok cool, agreed.
