### ISSUE TITLE
change select default display text

### ISSUE THREAD

**Issue by kennethbigler** [bvaughn/react-virtualized-select#68]
Default text is always "Select..."

Can we get this to be customizable? As a prop maybe?

**Comment by bvaughn** [comment]
I believe you're actually looking for the [`placeholder` prop](https://github.com/JedWatson/react-select/blob/6c0ee59ec82d4f25987571ac175cec7846c2d7d1/src/Select.js#L1148) of `react-select` 😄

**Comment by bvaughn** [comment]
To be clear, `react-virtualized-select` [passes through all props](https://github.com/bvaughn/react-virtualized-select/blob/35e950b1f7036c1d7865b8132a152f667db20ad9/source/VirtualizedSelect/VirtualizedSelect.js#L55) to `react-select`, including `placeholder` 😄

**Comment by kennethbigler** [comment]
Thank you! Sorry I did not see that anywhere in the documentation but it is very clear in the implementation.

**Comment by bvaughn** [comment]
No worries 😄  You're not the first to be thrown by the relationship between the 2 libs
