### ISSUE TITLE
UMD distribution warns isMounted is deprecated

### ISSUE THREAD

**Issue by jharwig** [bvaughn/react-virtualized-select#69]
```
react.js Warning: AutosizeInput: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.
```

virtualized-select depends on `react-select@^1.0.0-rc.2`, which depends on `react-input-autosize@^1.1.0`. The warning is fixed in version `1.1.3` of React-Input-Autosize.

I cloned the repo and ran a clean build using the `3.0.1` tag (should that be `3.1.0`?) and the build was okay so something must have gone wrong when publishing. Maybe a shrink-wrap or yarn lock file is to blame?

Verified by this shell script:
```sh
$ npm install react-virtualized-select@3.1.0 && \
  cat node_modules/react-virtualized-select/dist/umd/react-virtualized-select.js | \
  grep "this.isMounted"
```

A version bump and clean build should be enough to get the fixed version, but the version could also be updated to latest rc (which sets the autoresize version to `^1.1.3`.)

```diff
-"react-select": "^1.0.0-rc.2",
+"react-select": "^1.0.0-rc.5",
```

**Comment by bvaughn** [comment]
The range `^1.0.0-rc.2` includes `^1.0.0-rc.5` so no version bump (in `package.json`) is necessary. Bumping the version would break compat for anyone using a version below `1.0.0-rc.5` which I don't want to do for something that isn't an error.

All that should be needed is to do a fresh install (to pull in the newer react-select RC) and then rebuild the UMD version. I'll get to it at some point. 😄
