### ISSUE TITLE
Dropdown opens after clear after reselecting menu

### ISSUE THREAD

**Issue by turnerniles** [bvaughn/react-virtualized-select#71]
It seems react-virtualized-select opens the menu on clear after selecting an option then reselecting the menu, and then off click before clearing. In comparison react-select does not behave this way. See GIFs below. Do you think this is a react-virtualized-select or react-select bug?

We are experiencing a similar bug where the react-virtualized-select dropdown opens on clear without doing the below but I haven't figured the exact cause. I will post another issue once I get to the bottom of exactly what is causing it. Perhaps your insight on this issue will help me solve that one.

![reactvirtualizedselect](https://user-images.githubusercontent.com/8146241/28699111-b0eed37a-7315-11e7-92ed-2970caedf756.gif)

---------------------------

![reactselect](https://user-images.githubusercontent.com/8146241/28699113-b3e1a882-7315-11e7-9b05-84d8b84a61bf.gif)

**Comment by bvaughn** [comment]
Hm. I'm not seeing the behavior you show for react-virtualized-select:
![no-repro](https://user-images.githubusercontent.com/29597/28723234-0402e7fe-736b-11e7-97f9-08ff737fc4a8.gif)

I'd be happy to review a PR from you if you look into this though 😄  Unfortunately I don't have time to look because I'm swamped with work stuff.

**Comment by turnerniles** [comment]
@bvaughn You didn't re-select the menu after selecting an option before clearing if that makes sense. It may be an edge case but I will take a deeper look.

**Comment by turnerniles** [comment]
@bvaughn To clarify the issue.

1. You select an option. 
2. You click outside the dropdown so it is not focused. 
3. Then you click clear
4. The option menu renders and pops open

If an option is selected and the dropdown is not focused and then you click clear, the menu will render.
If an option is selected and the dropdown is focused and then you click clear, the menu does not render.

In react-select, regardless of whether the dropdown is focused or unfocused, when you click clear it does not render the menu.

I will continue looking at the code. I can see that the optionRenderer is being called on dropdown unfocused clear but is not being called on focused clear. Still trying to figure out why.

Further gifs below:

react-virtualized-select unfocused clear bug:
![react-virtualized-select-unfocused-clear](https://user-images.githubusercontent.com/8146241/28739906-fcbe6880-73cc-11e7-9307-01e415b80414.gif)

react-virtualized-select focused clear:
![react-virtualized-select-focused-clear](https://user-images.githubusercontent.com/8146241/28739917-0d4c3f2e-73cd-11e7-83a3-acd6d92a9fcc.gif)

react-select unfocused clear desired behavior:
![react-select-unfocused-clear](https://user-images.githubusercontent.com/8146241/28739925-1f734440-73cd-11e7-87c7-99c7cb46eb21.gif)

**Comment by bvaughn** [comment]
Makes sense 😄 Let me know what you find

**Comment by turnerniles** [comment]
Hi @bvaughn, it seems like it is an issue in the custom menuRenderer react-select code. Looks like @tosho-ait had the same issue [here](https://github.com/JedWatson/react-select/issues/1348). If you would like we can close this issue and I will open an issue on react-select.

Some how [this._openAfterFocus](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L313) gets set to true when using the react-select custom menuRenderer and you click clear when the dropdown is not focused.

If we delete the line: [291](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L291), it fixes the issue but I'm not sure if it breaks anything else. All react-select tests pass and all examples seem the same to me with the line deleted.

**Comment by bvaughn** [comment]
Thanks for the update. Let's close this issue then and open one for
react-select. Cheers!

**Comment by turnerniles** [comment]
@bvaughn, thanks, I've posted the issue on the react-select repo here: [#1901](https://github.com/JedWatson/react-select/issues/1901)

**Comment by turnerniles** [comment]
@agirton's new PR #1902 fixes this issue.
