### ISSUE TITLE
Key/value

### ISSUE THREAD

**Issue by steveareeno** [bvaughn/react-virtualized-select#72]
Is there a way to specify, in the control, what will be the key and value names when mapping the options? The control looks like it expects value/label. I have a json object that is Id/Name.

Thanks.

**Comment by steveareeno** [comment]
I think I might have found it in your example. It looks like I should use the following in the component:

```
<VirtualizedSelect
      **labelKey='Id'
      valueKey='Name'**
      options={options}
      onChange={(selectValue) => this.setState({ selectValue })}
      value={this.state.selectValue}
/>
```

**Comment by bvaughn** [comment]
Yup. 😄
