### ISSUE TITLE
Creatable - Long text

### ISSUE THREAD

**Issue by Subha** [bvaughn/react-virtualized-select#77]
Thanks for this multiple components(multi select, single select and Creatable) combined into one selectBox.
I have couple of issues/questions using Creatable :

1. when entering long text the width of the input box keeps growing is there a way to control this?
2. Ellipses are displayed on the field for long text but not able to place cursor pointer at the end.
Not able to edit it also. To enter value we need to delete it and re-enter.

**Comment by bvaughn** [comment]
Hey @Subha.

I think you meant to file this issue against [JedWatson/react-select](https://github.com/JedWatson/react-select). 😄
