### ISSUE TITLE
Disable an specific option

### ISSUE THREAD

**Issue by mcampagonzalez** [bvaughn/react-virtualized-select#78]
Disabling an specific option does not work following the react-select approach. Is there any tweak necessary for this to work? Thanks in advance :)

**Comment by bvaughn** [comment]
I'm guessing you found a solution to this before I had a chance to respond. :smile:

But for others that might find this question, you'd use `option.disabled` in your custom renderer. react-virtualized-select provides a default option renderer that already [checks this attribute](https://github.com/bvaughn/react-virtualized-select/blob/e012b456d8fab42dc527fe9dcb57f77dc3ff773e/source/VirtualizedSelect/VirtualizedSelect.js#L161-L163. So it should work just like react-select basically.
