### ISSUE TITLE
Force VirtualizedSelect to load options after onChange.

### ISSUE THREAD

**Issue by kimcrab** [bvaughn/react-virtualized-select#81]
Hi there, I have a problem with showing options after I select value.

Even after I select some option on the list through auto complete, It does not entered into the input filed because selected value does not exists on the option list. I guess this is happening because the number of options are limited.

Let's say I want to select 'zebra' so I searched 'ze' and 'zebra' is on the list because any other words that does not contain 'ze' will be filtered. So I select 'zebra' but once I select 'zebra', zebra is actually selected but now showing on the input field because 'zebra' is not on the options list because there are too many words over 'zebra' let's say 'apple', 'bear', 'car' and many more.

I want to load options with search words 'ze' after onClick method called but currently it seems **loadOptions** are not called after onClick.
How can I solve this problem?

**Comment by kimcrab** [comment]
`<VirtualizedSelect
      {...(!(option.param && option.param.parent) ? {} : { cache: false })}
      searchable={false}
      ignoreCase={true}
      placeholder={option.creatable ? msg.typeOrSelect : msg.select}
      selectComponent={
        option.creatable
          ? option.async ? AsyncCreatable : Creatable
          : option.async ? Select.Async : Select
      }
      loadOptions={loadOptions}
      {...props}
      onChange={onChange(props)}
      onBlur={noop}
      {...opts}
    />`

**Comment by bvaughn** [comment]
I think maybe you should ask this question on the [`react-select`](https://github.com/JedWatson/react-select) repo.

`react-virtualized-select` is a tiny wrapper around react-select that plugs [`react-virtualized`](https://github.com/bvaughn/react-virtualized/) into the options display so it can perform better. The source for it is actually [very small](https://github.com/bvaughn/react-virtualized-select/blob/master/source/VirtualizedSelect/VirtualizedSelect.js) and does not even reference the `loadOptions` property you mention. That property belongs to `Select.Async` in `react-select`. 😄
