### ISSUE TITLE
react-select and react-virtualized as peerDeps

### ISSUE THREAD

**Issue by Apercu** [bvaughn/react-virtualized-select#82]
Hey, just wanted to open the discussion regarding the fact that maybe react-select and react-virtualized should be peerDeps rather than fixed dependencies, allowing people to use their own versions?

There will be more installation hassle and some incompatibility issues but we can deal with those using specific ranges, still it allows to be more flexible.

For people interested, I've forked and published `react-virtualized-select-peer` in the meantime.

**Comment by bvaughn** [comment]
If you're using Yarn, people can always choose their own versions of the dependencies via a `resolutions` map in the `package.json`. If you're using NPM you should just be able to directly `npm install component@version --save` I think. Is this not true?

**Comment by Apercu** [comment]
That's a solution I guess, thanks ;)

**Comment by bvaughn** [comment]
No problem! And I appreciate the proposal/discussion!

I'd like to make installation painful for the fewest number of people, and support the most common use-cases. I _think_ the current approach does that but...I might be wrong and I'm open to changing my mind 😄
