### ISSUE TITLE
How to dynamically import?

### ISSUE THREAD

**Issue by ConAntonakos** [bvaughn/react-virtualized-select#83]
@bvaughn Thanks for this awesome library extending `react-select`. I'm having some issues trying to understand and utilize this in a dynamic way using webpack.

When I try to `await import('react-virtualized-select')`, I notice an object is returned with `{ default: function..., __esModules: true }`. What's the best way to proceed? Sorry, I'm a novice when it comes to understanding how dynamic imports have changed ES modules. I would love to contribute if there is a need. Thanks!

**Comment by bvaughn** [comment]
I don't really know much about the `await import` syntax, but I don't think your question is specific to this library. `react-virtualized-select` is exported as the default, meaning that you'd normally import it like so:

```js
import Select from 'react-virtualized-select';
```

Looks like the dynamic import is returning a module object with a `default` property that you'll need to access it at instead, so:
```js
const module = await import('react-virtualized-select');
const Select = module.default;
```

This is just my guess ^ I haven't tried it 😁

**Comment by ConAntonakos** [comment]
Thanks for your response, @bvaughn.

I definitely tried doing what you displayed in the next two-line example, but still couldn't get it to work. The `default` property returns a named function called VirtualizedSelect, and I couldn't instantiate that as a React.Element.

Anyway, I'll keep playing around, but wasn't sure if it was something that needs to change in the way it's being exported. And perhaps it'll help someone else out if they find it. Thanks for your time!

**Comment by bvaughn** [comment]
> The default property returns a named function called VirtualizedSelect, and I couldn't instantiate that as a React.Element.

What do you mean by this? What did you try doing and what error message did you receive?
