### ISSUE TITLE
menu list hover missing pointer: cursor

### ISSUE THREAD

**Issue by ShockiTV** [bvaughn/react-virtualized-select#86]
no such thing like
```
.VirtualizedSelectOption {
    cursor: pointer;
}
```

**Comment by bvaughn** [comment]
I don't think it needs a cursor pointer by default. If you want one for your application, you can add it using the CSS you've provided above. 😄

**Comment by ShockiTV** [comment]
Just wanted same behaviour to standard react-select.
OK

**Comment by bvaughn** [comment]
Ah, I see. I didn't realize `react-select` had that behavior by default. Hmm 🤔  I guess it's reasonable to copy that behavior here too then.

**Comment by bvaughn** [comment]
Shoot me a PR if you'd liek to add this 😄
