### ISSUE TITLE
seems incompatible with React 16

### ISSUE THREAD

**Issue by UtillYou** [bvaughn/react-virtualized-select#89]
When using in React 16, I got an error:

`invariant.js:42 Uncaught Error: Element ref was specified as a string (value0) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).`

After some googles, I think this is mainly caused by that this package requires React 15, besides this package used 'ref'. Can we update the version?

**Comment by bvaughn** [comment]
`react-virtualized-select` doesn't require `react` as a dependency, but rather as a [peer dependency](https://github.com/bvaughn/react-virtualized-select/blob/9defd7a198742fa5288fa80f471d409c28401c09/package.json#L127-L130). So whatever's installing the 2nd copy of `react` is in your application code or another module.

If you're using Yarn, you can find out which package(s) require `react` by running:
```sh
yarn why react
```

Good luck!

**Comment by UtillYou** [comment]
Yes, `react-virtualized-select` does not relies on `react`, but it relies on `react-select`. However, `react-select` depends on `react` 15. Maybe I should raise an issue to `react-select`.
Thanks anyway!
