### ISSUE TITLE
Items not formatting correctly depending on width

### ISSUE THREAD

**Issue by leojh** [bvaughn/react-virtualized-select#9]
If the width of the component is small or text is too large, then they jumble together. This is inherent to this component and not something that happens in ```react-select```

**react-select**
![screen shot 2016-06-01 at 9 42 33 pm](https://cloud.githubusercontent.com/assets/1440435/15731282/d7008d76-2841-11e6-8fcd-cfd70749e4b2.png)

**react-virtualized-select**
![screen shot 2016-06-01 at 9 42 45 pm](https://cloud.githubusercontent.com/assets/1440435/15731285/df20a45a-2841-11e6-916c-93f09ae292c1.png)

**Comment by leojh** [comment]
@bvaughn I guess I thought it should render just like `react-select` but you bring up a good point about styles introduced by `react-virtualized` 

I will spend some more time looking at this from that angle, let's leave this open for now if that's ok with you while I look at it.

**Comment by bvaughn** [comment]
Gotcha. With react-virtualized, you're making a bit of a tradeoff. You gain performance but you sacrifice a bit of flexibility.

With v7 react-virtualized, this is less an issue- because there are HOCs like `CellMeasurer` to help with just-in-time measuring and dynamic heights of rows. That functionality isn't exposed in react-virtualized-select though. (Maybe it could be?) At the moment though, it expects pre-determined heights.

**Comment by leojh** [comment]
perfect. I'll be taking a look for sure within the next few days. have to clear out some other things first :)

**Comment by bvaughn** [comment]
Any update on this issue from your end, @leojh ? Just curious if you were able to find a work-around or any new ideas. I haven't spent much time thinking about it, admittedly.

**Comment by leojh** [comment]
@bvaughn admittedly, no :) I will be finishing up with my feature here prob in a week or so have this is on the final "polishing up" list that I have so I will be getting to it then. 

**For anyone dealing with this, a simple workaround is just to increase width of dropdown enough for it not be an issue**

**Comment by bvaughn** [comment]
No problem :) Let's chat more then when you get back to it.

**Comment by bvaughn** [comment]
Spent a couple of hours looking into this feature request over the weekend and it seems a bit more complicated to support than I initially suspected. I have it partially working but there are some unhandled edge-cases that I wasn't able to resolve.

**Comment by leojh** [comment]
I can always import your changes in my project and take a look there

**Comment by bvaughn** [comment]
Sure. I'll push up my work-in-progress branch at some point after work today.

**Comment by bvaughn** [comment]
Sorry @leojh! Slipped my mind after work.

Just pushed branch [`issues/9`](https://github.com/bvaughn/react-virtualized-select/tree/issues/9) if you'd like to take a look. It's very much a work-in-progress. I just ran out of time at the moment. :)

**Comment by bvaughn** [comment]
I am going to close this issue for now because I don't plan on taking any action on it at the moment. Happy to continue talking about it and to look over any PR if you decide to share a possible solution though! :)

**Comment by mbrevda** [comment]
I'm having what I believe is a similar issue, the select box doesn't grow to fit it's content:

<img width="103" alt="screen shot 2016-08-29 at 5 21 23 pm" src="https://cloud.githubusercontent.com/assets/293004/18054608/42a701a2-6e0d-11e6-9dd0-356fc62a7697.png">


Here are my changes to the css, I don't think they should be affecting anything:
```scss
@import "../../node_modules/react-select/scss/select.scss";
$select-input-border-width: 0;
$select-input-border-radius: 0;
$select-option-bg: $topbar-bg;
$select-input-bg: $topbar-bg;

$select-text-color: inherit;
$select-input-placeholder: inherit;

@import "../../node_modules/react-select/scss/control";
@import "../../node_modules/react-select/scss/menu";
@import "../../node_modules/react-select/scss/mixins";
//@import "../../node_modules/react-select/scss/multi";
```

Am I doing something wrong?

**Comment by bvaughn** [comment]
Hey @mbrevda,

Those styles belong to `react-select` (not `react-virtualized-select`) so maybe this comment is in the wrong place? `react-virtualized-select` doesn't come into play until the select menu is opened; (it renders the drop-down part).

**Comment by mbrevda** [comment]
Yup, wrong repo. Thanks!

**Comment by bvaughn** [comment]
No problem! :D
