### ISSUE TITLE
OnBlur not firing.

### ISSUE THREAD

**Issue by Subha** [bvaughn/react-virtualized-select#91]
I am not able to recreate the issue in the demo page.
http://bvaughn.github.io/react-virtualized-select/. 

I have a similar issue in my project and was able to recreate the issue when i cloned this repo today.

Steps to recreate:

1. Click the dropdown Arrow.
2. Without selecting any options I selected another dropdown and the dropdowns never got closed.

I have attached a snapshot of my issue. 

Expected Behaviour:

I expect the onBlur gets called when I clicked on the next dropdown(arrow Button). But the onBlur never got fired. 

Is anyone facing this issue? 

![screen shot 2017-12-11 at 4 11 10 pm](https://user-images.githubusercontent.com/12513265/33855595-5fbdf96a-de93-11e7-9c2b-44d58770dd51.png)

Any help is greatly appreciated.

Thank you
Anu

**Comment by bvaughn** [comment]
Seems pretty likely that this issue should actually be filed against [react-select](https://github.com/JedWatson/react-select) 😄  This project just renders the drop-down list. The open/close state (and most everything else) is managed by react-select.

Cheers!

**Comment by Subha** [comment]
Thank you. Looks like they updated to a new version and that is causing this issue
