### ISSUE TITLE
Update react-select

### ISSUE THREAD

**Issue by sugarshin** [bvaughn/react-virtualized-select#92]
Hi,

Please update version of `react-select` , because there are functions that can not be used now.
Latest version is `1.1.0` . Thank you!

**Comment by bvaughn** [comment]
You can do this yourself. This package specifies [any version after ^.0.0-rc.2](https://github.com/bvaughn/react-virtualized-select/blob/master/package.json#L124). You can update to 1.1.0 in your project.

**Comment by ConAntonakos** [comment]
Yeah, I solved this by reinstalling the package via `yarn`. Is there a better method to this?

**Comment by turnerniles** [comment]
@ConAntonakos Perhaps ```yarn upgrade```?
