### ISSUE TITLE
Cannot install dev dependencies

### ISSUE THREAD

**Issue by julien-f** [bvaughn/react-virtualized-select#93]
```
$ node -v
v0.9.3
$ yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > babel-eslint@5.0.4" has unmet peer dependency "eslint@<2.3.0".
warning " > babel-loader@6.4.1" has unmet peer dependency "babel-core@^6.0.0".
[4/4] Building fresh packages...
[1/3] ⡀ execSync: [execsync v1.0.2] Attempting to compile native extensions.
[2/3] ⡀ phantomjs
[-/3] ⡀ waiting...
[-/3] ⡀ waiting...
error /react-virtualized-select/node_modules/phantomjs: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /react-virtualized-select/node_modules/phantomjs
Output:
PhantomJS not found on PATH
Phantom installation failed TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.join (path.js:1244:7)
    at findSuitableTempDirectory (/react-virtualized-select/node_modules/phantomjs/install.js:127:30)
    at /react-virtualized-select/node_modules/phantomjs/install.js:476:19
    at nextTickCallback (/react-virtualized-select/node_modules/kew/kew.js:47:28)
    at process._tickCallback (internal/process/next_tick.js:150:11) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.join (path.js:1244:7)
    at findSuitableTempDirectory (/react-virtualized-select/node_modules/phantomjs/install.js:127:30)
```

Also a lot of dependencies are out of date, it would probably be good to update them 😃

**Comment by bvaughn** [comment]
This looks like something went wrong with your Yarn installation? I'm not sure what I can do to help with this. [PhantomJS is declared as an explicit dependency.](https://github.com/bvaughn/react-virtualized-select/blob/9defd7a198742fa5288fa80f471d409c28401c09/package.json#L101)

If you'd like to update dev-deps, feel free to submit a PR. Assuming it doesn't break anything, I'd be happy to merge it. 😄  Not a high priority for me though at the moment.

**Comment by julien-f** [comment]
I don't know what to tell you, my Yarn is up-to-date and I just cloned the repo 😕 

I don't want to update deps if cannot run the tests.

**Comment by bvaughn** [comment]
> I don't want to update deps if cannot run the tests.

Understandable. 😄 

I'm sorry I don't have time to troubleshoot Yarn issues. 🙁  Hope you're able to figure it out.

**Comment by turnerniles** [comment]
I'm getting a different error which is thrown because of the linter.

```yarn
yarn install v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "babel-eslint@5.0.4" has unmet peer dependency "eslint@<2.3.0".
[4/4] 📃  Building fresh packages...
$ npm run build

> react-virtualized-select@3.1.0 prebuild /Users/admin/dev/react-virtualized-select
> npm run lint


> react-virtualized-select@3.1.0 lint /Users/admin/dev/react-virtualized-select
> standard

standard: Use JavaScript Standard Style (https://github.com/feross/standard)
  /Users/admin/dev/react-virtualized-select/source/demo/data/cities.js:927:2: Extra semicolon.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-virtualized-select@3.1.0 lint: `standard`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-virtualized-select@3.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2018-01-05T06_01_50_803Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-virtualized-select@3.1.0 prebuild: `npm run lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-virtualized-select@3.1.0 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2018-01-05T06_01_50_827Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.```

@julien-f why are you using node v0.9.3

**Comment by turnerniles** [comment]
@julien-f @bvaughn I'm on node v8.6.0 and it works up until you run `npm run lint` as per above. I put up a PR #94 to fix the issue `/Users/admin/dev/react-virtualized-select/source/demo/data/cities.js:927:2: Extra semicolon.`. Even though there is no extra semi colon...

**Comment by bvaughn** [comment]
The lint error was expected. Not sure how it snuck in. I had fixed locally and forgot to push. (Thanks for your PR to fix!)

This looks like an env or Node version problem being reported. Given the inability to reproduce it, and the lack of response on this issue after a few days, I'm going to close it. 👍

**Comment by julien-f** [comment]
@turnerniles I meant 9.3.0 😁

**Comment by turnerniles** [comment]
@julien-f that makes more sense! It works for me with node v9.3.0. Are you able to `yarn install` now?

**Comment by julien-f** [comment]
Nope, `yarn` fails to install `phantomjs`, but `npm` succeeds.

It also appears that it does not fail if `phantomjs` has been previously installed globally and is available in the PATH (which I believe is the case for all of you).

**Comment by turnerniles** [comment]
@julien-f that is weird. `yarn` / `yarn install` works for me without having phantomjs installed globally when pulling down a fresh copy of the latest. `npm run test` doesn't work but `yarn` / `yarn install` -> `npm run start` to see the demo without error. I'm not sure what the discrepancy could be.
