### ISSUE TITLE
Documentation Inconsistency

### ISSUE THREAD

**Issue by seanfrisbey** [bvaughn/react-virtualized-select#97]
In the demo with the country flags, the CountryOptionRenderer takes "key" as a parameter, but "key is not mentioned in the documentation for what's passed into the optionRenderer. Which is correct? If key IS passed, can the documentation be updated to reflect its purpose?

Thanks!

**Comment by bvaughn** [comment]
Ah. The docs should be updated to mention this attribute. Would you be willing to do this? 😄 

[Keys provide important performance hints to React, enabling it to avoid unnecessary re-renders.](https://reactjs.org/docs/lists-and-keys.html)

**Comment by seanfrisbey** [comment]
Sure thing! Thanks ;)

**Comment by seanfrisbey** [comment]
I think I submitted the changes...do you have to approve them?

**Comment by bvaughn** [comment]
Where did you submit them?

You should create a PR to this repo with an update to [this `README.md` file](https://github.com/bvaughn/react-virtualized-select/blob/master/README.md)

**Comment by seanfrisbey** [comment]
I think it did it properly this time.

**Comment by bvaughn** [comment]
Yeah I see the PR this time 👍
